"""add paid_at to orders

Revision ID: ce202e1763ab
Revises: edbcbe791bfa
Create Date: 2026-08-16 03:58:26.868227

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce202e1763ab"
down_revision: str | Sequence[str] | None = "edbcbe791bfa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "paid_at")
    # ### end Alembic commands ###
